version: '3'
services:
  db:
    restart: always
    image: "mysql:5"
    environment:
      MYSQL_DATABASE: vehicle
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ROOT_HOST: '%'
    networks:
      - backend
    ports:
      - 3306:3306

  vehicleapp:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: on-failure
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/vehicle?autoReconnect=true&useSSL=false
      PROFILE: stg
    expose:
      - "8080"
    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      - backend


networks:
  backend: